AppLensV2/AppLensV2.csproj
AppLensV2/Controllers/SitesController.cs
AppLensV2/Helpers/GithubClient.cs
AppLensV2/Web.config
AppLensV2/app/Common/Constants.ts
AppLensV2/app/Common/DetectorsService.ts
AppLensV2/app/Detector/DetectorViewDirective.ts
AppLensV2/app/Detector/detectorview.html
AppLensV2/app/app.ts
AppLensV2/app/assets/app.css
AppLensV2/bower.json
AppLensV2/index.html
Documents/servicehealth/solution.md
Documents/servicehealth/wiki.md

The PR contains:
- Basic  Document Structure for detector
- Ability to read solutions and wiki for each detector
- Render markdown documents in app

Git Document work for detector's wiki and solution

---

AppLensV2/Helpers/GeoRegionClient.cs
AppLensV2/app/Common/Constants.ts
AppLensV2/app/Common/DetectorsService.ts
AppLensV2/app/Common/IStateParams.ts
AppLensV2/app/Detector/DetectorCtrl.ts
AppLensV2/app/Detector/DetectorViewHelper.ts
AppLensV2/app/Main/MainCtrl.ts
AppLensV2/app/NgModels/DetectorResponse.ts
AppLensV2/app/Sia/SiaCtrl.ts
AppLensV2/app/app.ts

This change includes everything to allow for you to specify time change in the query string. There are also a few bug fixes that I found while merging.

Add time grain

---

AppLensV2/AppLensV2.csproj
AppLensV2/Helpers/GeoRegionClient.cs
AppLensV2/Helpers/GithubClient.cs
AppLensV2/app/Detector/DetectorCtrl.ts
AppLensV2/app/Detector/DetectorViewDirective.ts
AppLensV2/app/Detector/DetectorViewHelper.ts
AppLensV2/app/Detector/detector.html
AppLensV2/app/Detector/detectorview.html
AppLensV2/app/Main/MainCtrl.ts
AppLensV2/app/Main/main.html
AppLensV2/app/NgModels/Detector.ts
AppLensV2/app/Sia/SiaCtrl.ts
AppLensV2/app/Sia/sia.html
AppLensV2/app/app.ts
AppLensV2/app/assets/app.css
AppLensV2/app/assets/svg/search.svg
AppLensV2/app/assets/svg/success.svg
AppLensV2/app/assets/svg/warning.svg

Changes:
1. App Analysis API Integration + UI (issue#30)
2. Use ETAG for github API call (issue#27)

App Analysis work

---

AppLensV2/app/Detector/detectorview.html
AppLensV2/app/assets/app.css

Add github edit button for the solution and wiki documents

---

AppLensV2/Helpers/GeoRegionClient.cs
AppLensV2/app/Detector/DetectorViewHelper.ts

Remove filter on memory graphs now that there is only one series

---

AppLensV2/app/Detector/DetectorViewDirective.ts
AppLensV2/app/Detector/detector.html
AppLensV2/app/Detector/detectorview.html

Now it is just basic table thos show name-value pairs from addtional
data

Additional Data UI

---

AppLensV2/Helpers/GeoRegionClient.cs
AppLensV2/app/NgModels/SiaResponse.ts
AppLensV2/app/Sia/SiaCtrl.ts
AppLensV2/app/Sia/sia.html

Added solution, data source, and wiki to sia output where it was missing

Fixsiaoutput

---

AppLensV2/app/Detector/DetectorViewHelper.ts

The logic before was doing costly filters and scans on large data sets. The old method for data sets that contained numerous workers would take over 2 seconds just to create the data to graph. With these changes it is now around 30ms max

Updating the logic for generating graph data

---

AppLensV2/app/NgModels/DetectorResponse.ts
AppLensV2/app/NgModels/SiaResponse.ts
AppLensV2/app/Sia/SiaCtrl.ts
AppLensV2/app/Sia/sia.html

Collapsabletimeperiod

---

AppLensV2/AppLensV2.csproj
AppLensV2/Helpers/ConfigHelper.cs
AppLensV2/Helpers/SupportObserverClient.cs
AppLensV2/Web.config

+Remove key to observer API
+Add a somewhat more secure way to the key
Need to blacklist this key since the key is still in git commit history so anyone still has access to the key and can potentially use it

Remove hash key

---

AppLensV2/app/Common/DetectorsService.ts
AppLensV2/app/Main/MainCtrl.ts
AppLensV2/app/Main/main.html
AppLensV2/app/NgModels/Detector.ts
AppLensV2/app/NgModels/SiaResponse.ts
AppLensV2/app/app.ts

badges for detectors

---

AppLensV2/AppLensV2.csproj
AppLensV2/app/Common/FeedbackService.ts
AppLensV2/app/Main/MainCtrl.ts
AppLensV2/app/Main/main.html
AppLensV2/app/app.ts

Add a button that will allow the users to email us with feedback. Also add a toast that will make people aware of this change while they are using the site.

Feedbackbuttons

---

AppLensV2/AppLensV2.csproj
AppLensV2/app/Common/DetectorsService.ts
AppLensV2/app/Common/SiaService.ts
AppLensV2/app/Detector/DetectorViewDirective.ts
AppLensV2/app/Detector/detectorview.html
AppLensV2/app/DowntimeTimeline/DowntimeTimelineDirective.ts
AppLensV2/app/DowntimeTimeline/downtimetimeline.html
AppLensV2/app/Main/MainCtrl.ts
AppLensV2/app/Main/main.html
AppLensV2/app/Sia/SiaCtrl.ts
AppLensV2/app/Sia/sia.html
AppLensV2/app/app.ts
AppLensV2/app/assets/app.css

Add a directive above the graphs that highlight which abnormal time
period you are looking at. Also change the navigation so that you move
left and right between abnormal time periods and you can also jump to a
specific downtime by clicking on the timeline

Sia Downtime Timeline and Navigation Change

---

AppLensV2/app/Main/MainCtrl.ts

Remove the toast that was highlighting the new feedback feature

Removetoast

---

AppLensV2/Controllers/SitesController.cs
AppLensV2/Helpers/SupportObserverClient.cs
AppLensV2/app/Common/SiteService.ts
AppLensV2/app/Detector/DetectorViewHelper.ts
AppLensV2/app/Main/MainCtrl.ts

Add a subsequent call to observer in order to get resource group name which we will need for perf mon detectors and if we want to make a call to metrics

Perfmoncounters

---

AppLensV2/AppLensV2.csproj
AppLensV2/Controllers/SitesController.cs
AppLensV2/Helpers/GeoRegionClient.cs
AppLensV2/Helpers/SupportObserverClient.cs
AppLensV2/app/Common/DetectorsService.ts
AppLensV2/app/Common/ErrorHandlerService.ts
AppLensV2/app/Common/SiteService.ts
AppLensV2/app/Detector/DetectorCtrl.ts
AppLensV2/app/Main/MainCtrl.ts
AppLensV2/app/NgModels/ErrorModel.ts
AppLensV2/app/Sia/SiaCtrl.ts
AppLensV2/app/app.ts

This PR contains:
- Observer API error handling.
- Diagnostic Role API error handling

Handle client and server Errors

---

AppLensV2/AppLensV2.csproj
AppLensV2/Helpers/GeoRegionClient.cs
AppLensV2/Helpers/SupportObserverClient.cs
AppLensV2/Web.config
AppLensV2/app/Common/SiteService.ts
AppLensV2/app/Main/MainCtrl.ts
AppLensV2/app/Main/main.html
AppLensV2/app/MultipleSitesDialog/MultipleSitesDialogCtrl.ts

In the case that for a given hostname there exist multiple sites, force the user to decide which site they want to investigate by choosing an option in a dialog box (see image below)
See issue #142

Account for multiple stamps

---

AppLensV2/Web.config

Update Web Config Rewrite Rule

---

AppLensV2/app/Detector/DetectorViewHelper.ts

Found another bug in detailed graph that causes it not to render

Fixdetailedgraphbug

---

AppLensV2/Controllers/SitesController.cs
AppLensV2/app/Common/Constants.ts
AppLensV2/app/Common/FeedbackService.ts
AppLensV2/app/Detector/DetectorViewDirective.ts
AppLensV2/app/Detector/detectorview.html
AppLensV2/app/Main/MainCtrl.ts
AppLensV2/app/Main/main.html
AppLensV2/app/app.ts

The PR contains:
- Feedback option for cases.
- Opening new github issue directly from applens.
- Detector Like/Dislike option.
- All these telemetry captured in App insights.

Feedback Additions to applens

---

AppLensV2/Controllers/SitesController.cs
AppLensV2/app/Common/SiteService.ts

This reverts commit 8f36b79c124605a56bd89fd03cfe56ce395a0b69. This is to temporarily fix issue #268

Revert "Derive main site from site array"

---

AppLensV2/Helpers/ConfigHelper.cs
AppLensV2/Helpers/GeoRegionClient.cs
AppLensV2/Web.config
AppLensV2/app/Main/MainCtrl.ts
AppLensV2/app/app.ts
AppLensV2/bower.json
AppLensV2/index.html

Changes:
-
- Handle browser issue 
- Remove thumbprint from code. As a result, for Local debugging create %USERPROFILE%\GeoRegionAuthCertThumbprint.txt and place your thumbprint here

Warning message for browsers other than chrome

---

AppLensV2/AppLensV2.csproj
AppLensV2/app/Home/HomeCtrl.ts
AppLensV2/app/Home/home.html
AppLensV2/app/app.ts

As discussed. I forked the tree rather than branch it. 
I was testing from home and got errors once I had re-directed to  the Main /sites/Sitename and so I will test again tomorrow in the office.

Home Page for SiteName only

---

AppLensV2/app/Home/HomeCtrl.ts
AppLensV2/app/Home/home.html
AppLensV2/app/app.ts
AppLensV2/bower.json
AppLensV2/index.html

Implemented the material date time picker. 
Please note that I needed to add another version of Moment.Js and that the Material Date Time Picker needed an edit as per https://github.com/logbon72/angular-material-datetimepicker/issues/80. 
The date passing format isn't working properly just yet and I can talk to you about this tomorrow.

DateTimePicker Changes.

---

AppLensV2/app/Detector/DetectorViewHelper.ts

Changing from 'Wed 11:23 PM' to '01/26 23:23'
**OLD:**
this was bug in nvd3 caused by interactive guideline:
**NEW:**

Fixing Date Format for bar chart and changing it for all

---

AppLensV2/app/Detector/DetectorViewDirective.ts
AppLensV2/app/Detector/detectorview.html
AppLensV2/app/NgModels/Detector.ts
AppLensV2/app/Sia/SiaCtrl.ts
AppLensV2/app/Sia/sia.html
AppLensV2/app/app.ts
AppLensV2/app/assets/app.css
AppLensV2/bower.json
AppLensV2/index.html

- Changes to show Additional Data
- Include reason for w3wp stop event

Show Additional Data

---

AppLensV2/AppLensV2.csproj
AppLensV2/app/Common/DetectorsService.ts
AppLensV2/app/Common/SiaService.ts
AppLensV2/app/DowntimeTimeline/DowntimeTimelineDirective.ts
AppLensV2/app/Home/HomeCtrl.ts
AppLensV2/app/Main/MainCtrl.ts
AppLensV2/app/Main/main.html
AppLensV2/app/Sia/SiaCtrl.ts
AppLensV2/app/Site/SiteCtrl.ts
AppLensV2/app/Site/site.html
AppLensV2/app/app.ts

Making the main part of the page controlled by the SiteCtrl instead of
the MainCtrl, so that we can reuse the MainCtrl even if we want to
display different data in the main area (Latency, ASE). Changing the
states and renaming them to make it more clear.
Also renaming variable in Sia Service. I am using the same logic for naming that I do in the API. 
SIA = intelligent analysis
appanalysis and perfanalysis(not implemented yet) = type of sia.

Latency test

---

AppLensV2/app/Main/MainCtrl.ts
AppLensV2/app/Main/main.html
AppLensV2/app/Site/SiteCtrl.ts
AppLensV2/app/app.ts

Make the html reference the service directly, so that the list is
updated when the other controller updates the service data.
Also add a state for the old detectors path that redirects to the new
detectors path.

Detector List changes

---

AppLensV2/AppLensV2.csproj
AppLensV2/app/Common/DetectorsService.ts
AppLensV2/app/Common/SiaService.ts
AppLensV2/app/Common/TimeParamsService.ts
AppLensV2/app/Detector/DetectorCtrl.ts
AppLensV2/app/DowntimeTimeline/DowntimeTimelineDirective.ts
AppLensV2/app/Main/MainCtrl.ts
AppLensV2/app/Sia/SiaCtrl.ts
AppLensV2/app/Site/SiteCtrl.ts
AppLensV2/app/app.ts

Adding Service to keep track of time parameters so that each controller
doesn't need to do it. Also have the services pass these parameters as
well at site to each other instead of passing to the controller and
having the controller pass it back.
Let me know if there are any concerns about removing site and time from the input to the service functions.

Adding Time Params Service

---

AppLensV2/app/Detector/DetectorViewHelper.ts
AppLensV2/app/Main/main.html

Make Perf Analysis public

---

AppLensV2/AppLensV2.csproj
AppLensV2/app/Common/ThemeService.ts
AppLensV2/app/Main/MainCtrl.ts
AppLensV2/app/Main/main.html
AppLensV2/app/app.ts
AppLensV2/app/assets/app.css

Changetheme

---

AppLensV2/app/Common/FeedbackService.ts
AppLensV2/app/Detector/DetectorViewHelper.ts

also adding the new garbage collection endpoint to the line graph list

Updating email

---

AppLensV2/app/Sia/sia.html
AppLensV2/app/Site/SiteCtrl.ts
AppLensV2/app/Site/site.html

Ignore Analysis when SLA is met

---

AppLensV2/app/DetailDetector/DetailedDetectorViewDirective.ts
AppLensV2/app/DetailDetector/detaileddetectorview.html
AppLensV2/app/Detector/DetectorViewHelper.ts
AppLensV2/app/NgModels/GraphSeries.ts

There are too many sites in some cases that you can't even see the graph. This will remove series where no points exceed 0.5% and display a warning message

Detailed Graph View Limit Processes

---

AppLensV2/app/Detector/detectorview.html

Log details pop up

---

AppLensV2/app/Detector/DetectorCtrl.ts
AppLensV2/app/Detector/DetectorViewHelper.ts
AppLensV2/app/assets/app.css

Changes to FileSystemUsage detector

---

AppLensV2/app/Detector/detectorview.html
AppLensV2/app/Main/main.html

One other small change that is already deployed.

Update Observer Link

---

AppLensV2/Helpers/GeoRegionClient.cs
AppLensV2/app/Detector/DetectorViewHelper.ts
AppLensV2/app/Main/main.html
AppLensV2/app/Site/SiteCtrl.ts

Two changes:
1. Update views for percentile view for performance
2. Enable TCP connection analysis

Percentiles in Perf Analysis

---

AppLensV2/app/Common/Constants.ts

Sorry I didn't look at #799 Pull Request to closely. But that change broke ASELens. Need to revert portion of that change to get ASE working again.

Fix for ASE. Point back to v1 for ASE

---

AppLensV2/app/Analysis/sia.html

Notes
-Some solutions have verbose descriptions that help explain the problem and resolution really well. Show these descriptions on AppLensV2 under the analysis view.
-Increase the width of the div that contains the list of solutions to account for long detailed descriptions

Add description from solution

---

AppLensV2/AppLensV2.csproj
AppLensV2/app/AppServiceEnvironment/appServiceEnvironment.html
AppLensV2/app/AppServiceEnvironment/appServiceEnvironmentMain.html
AppLensV2/app/Common/DetectorsService.ts
AppLensV2/app/Detector/DetectorCtrl.ts
AppLensV2/app/Detector/DetectorViewDirective.ts
AppLensV2/app/Detector/ase_detector.html
AppLensV2/app/Detector/detector.html
AppLensV2/app/Detector/detectorview.html
AppLensV2/app/NgModels/DetectorResponse.ts
AppLensV2/app/app.ts

-Show observations and solutions on a per detector level
-Hide nvd3 graph for vnet verifier
-Show correlated detectors in detectors list for ASE Lens
1)
2)
3)

Show observations solutions in detector view

---

AppLensV2/app/Site/SiteCtrl.ts

rename platform to canary

---

AppLensV2/app/Common/Constants.ts
AppLensV2/app/Detector/DetectorCtrl.ts
AppLensV2/app/Detector/DetectorViewHelper.ts

This is for Issue #823 and #755 
- Change charting options for ASE Health Check Detector
- Append hostingEnvironmentName to the query string so that the ASE Health detector will pick it up

Include ase health check in analysis

---

AppLensV2/app/Incident/IncidentDirective.ts
AppLensV2/app/Incident/incidentdirective.html

Updating Icm notifications

---

AppLensV2/app/Incident/IncidentDirective.ts
AppLensV2/app/Incident/incidentdirective.html
AppLensV2/app/Site/site.html

Updating ICM notification views

---

AppLensV2/Kusto/KustoQueries.cs
AppLensV2/app/Incident/IncidentDirective.ts
AppLensV2/app/Incident/incidentdirective.html

Link to Network tool + small css changes

---

AppLensV2/Controllers/SitesController.cs
AppLensV2/Helpers/GeoRegionClient.cs
AppLensV2/app/AppServiceEnvironment/AppServiceEnvironmentCtrl.ts
AppLensV2/app/AppServiceEnvironment/appServiceEnvironmentMain.html
AppLensV2/app/Common/Constants.ts
AppLensV2/app/Common/DetectorsService.ts
AppLensV2/app/Common/SiaService.ts
AppLensV2/app/Common/SiteService.ts
AppLensV2/app/Main/MainCtrl.ts
AppLensV2/app/Main/main.html

and Adding change resource button
AJ wanted this button for when this is being used in iframe

Finally updating to SiteV3Controller
